# Argo CD setup
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/phdah/argoWorkflow.git
    targetRevision: HEAD
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---
# Setup all Argo CD
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/phdah/argoWorkflow.git
    targetRevision: HEAD
    path: app/argo/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---
# Setup all Argo Workflows
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflow
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/phdah/argoWorkflow.git
    targetRevision: HEAD
    path: app/argo/argoworkflow
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---
# Setup all Argo Events
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/phdah/argoWorkflow.git
    targetRevision: HEAD
    path: app/argo/argoevents
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---
# Application setup
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-service-test
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/phdah/kubernetesDemoApp.git
    targetRevision: HEAD
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: application

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
